### PR TITLE
Remove `en-us` from microsoft links, and fix a couple of dead links

### LINKED ISSUE #1979: Remove `en-us` from MSDN links
In C++ repo, CI even gives us an error if we don't.
Without `en-us`, the link works perfectly, but opens to everyone in their preferred language.

### PR DESCRIPTION
**Pull request by antkmsft**
Closes #1979

### CODE REVIEW

File: sdk/inc/azure/core/internal/az_precondition_internal.h [hunk 1]
```diff
@@ -51,7 +51,7 @@ az_precondition_failed_fn az_precondition_failed_get_callback();
 // earlier without verifying, because if __analysis_assume() is not available on earlier compiler
 // version, there will be a compilation error.
 // For more info, see
-// https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/using-the--analysis-assume-function-to-suppress-false-defects
```
Comment (ahsonkhan) [inline sdk/inc/azure/core/internal/az_precondition_internal.h:54]: I was going to ask why link verification didn't catch this, but guessing that since these are just links within doc comments, not an actual hyperlink within markdown or other such docs, it doesn't get validated.

@danieljurek, @weshaggard has this come up as a way to improve link verification in other languages? If we have typos in links within source code comments that could 404, should those be verified?

**Review by ahsonkhan — APPROVED** [review]
How did you initially notice these @antkmsft ?
And did you run some regex to find/fix them all?

File: sdk/inc/azure/core/internal/az_precondition_internal.h (hunk 1 above)
Comment (weshaggard) [reply sdk/inc/azure/core/internal/az_precondition_internal.h:54]: You are correct that we don't validate random links in any text we only look at well formed links in MD or html. This has come up in .NET XML doc comments recently, https://github.com/Azure/azure-sdk-for-net/issues/22216, although we don't have a solution for that currently either. It can be tricky to parse out links in random source code.

Comment (ahsonkhan) [reply sdk/inc/azure/core/internal/az_precondition_internal.h:54]: That's what I figured. Thanks!

Comment (antkmsft) [reply sdk/inc/azure/core/internal/az_precondition_internal.h:54]: #1980 Is about this, but based on @weshaggard's response, I think we can close it?

**Comment by antkmsft** [comment]
@ahsonkhan, no regexes, manual review. There aren't this many. Dead links I've found as I was still verifying each link I was removing `en-us` from. Initially I noticed this as I myself put a link with `en-us` during the Storage SDK development, and decided to see if there are other links like this, and found more.

**Comment by ahsonkhan** [comment]
> no regexes, manual review

Did you run a Ctrl+F (or find/search in an IDE like VS Code) to capture all instances of links with `en-us` in the repo?

**Comment by antkmsft** [comment]
@ahsonkhan, Ctrl+Shift+F for "en-us" in VS.
