### PR TITLE
fix custom iot user agent

### LINKED ISSUE #1984: Azure IoT Hub Client blindly copies user agent option
Thanks to @ewertons for finding.

Here we copy the user agent string and append it as a property. If the user sets it to a custom value, it gets appended without the "key" part of the "key value pair". 

https://github.com/Azure/azure-sdk-for-c/blob/c66093ab0da854ce071c2567a8b714e0f6a5a079/sdk/src/azure/iot/az_iot_hub_client.c#L104-L108

Aka
```c
options.user_agent = "xyz";

// This then gets appended as 
{iothubhostname}/{device_id}/?api-version=2018-06-30&xyz

// instead of 

{iothubhostname}/{device_id}/?api-version=2018-06-30&DeviceClientType=xyz
```

### PR DESCRIPTION
**Pull request by danewalton**
closes #1984

### CODE REVIEW

**Review by ericwol-msft — APPROVED** [review]

**Comment by danewalton** [comment]
waiting for @ewertons to clue in before merging

File: sdk/src/azure/iot/az_iot_hub_client.c [hunk 1]
```diff
@@ -21,13 +21,14 @@ static const az_span hub_client_param_equals_span = AZ_SPAN_LITERAL_FROM_STR("="
 
 static const az_span hub_digital_twin_model_id = AZ_SPAN_LITERAL_FROM_STR("model-id");
 static const az_span hub_service_api_version = AZ_SPAN_LITERAL_FROM_STR("/?api-version=2020-09-30");
-static const az_span client_sdk_version
-    = AZ_SPAN_LITERAL_FROM_STR("DeviceClientType=c%2F" AZ_SDK_VERSION_STRING);
+static const az_span client_sdk_device_client_type_name = AZ_SPAN_LITERAL_FROM_STR("dct");
```
Comment (ewertons) [inline sdk/src/azure/iot/az_iot_hub_client.c:24]: Love it!

**Review by ewertons — APPROVED** [review]
