### PR TITLE
Transform apply_credential into a HTTP policy

### LINKED ISSUE #799: Broken client-credential implementation for http request
After removing Mutex (https://github.com/Azure/azure-sdk-for-c/pull/771) we got a regression on keyvault sample where making a request with secret credential is not working anymore.

The issue is that the Authorization header value is getting corrupted in memory because it is set to a function scooped variable (see below code from https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/core/az_core/src/az_credential_client_secret.c#L55)
```c
  _az_token token = { 0 };
  AZ_RETURN_IF_FAILED(
      _az_credential_token_get_token(&credential->_internal.token_credential, &token));

  if (_az_token_expired(&token))
  {
    AZ_RETURN_IF_FAILED(_az_credential_client_secret_request_token(
        credential, ref_request->_internal.context, &token));

    AZ_RETURN_IF_FAILED(
        _az_credential_token_set_token(&credential->_internal.token_credential, &token));
  }

  int16_t const token_length = token._internal.token_length;

// ---> Here we add the auth header that points to a function scope variable.
//         MemAddress for variable will be reused as soon as we leave the function, corruption the header.
  AZ_RETURN_IF_FAILED(az_http_request_append_header(
      ref_request, _az_auth_header_name, az_span_init(token._internal.token, token_length)));

  return AZ_OK;
```

We need to think how we want to solve this.

-  Adding an extra buffer to request to keep the token (this would break refresh token and thread safe)
-  Pass the token_credential to transport http adapter (like libcurl) and let it call get_token to set header. This is basically moving the time for when we write the header, Request will not have this header.

Any other ideas? @gilbertw @ahsonkhan @JeffreyRichter

### PR DESCRIPTION
**Pull request by antkmsft**
Closes #799

### CODE REVIEW

File: sdk/core/az_core/inc/az_credentials.h [hunk 1]
```diff
@@ -73,8 +73,11 @@ typedef struct
  * @brief function callback definition as a contract to be implemented for a credential
  *
  */
-typedef AZ_NODISCARD az_result (
-    *_az_credential_apply_fn)(void* credential_options, _az_http_request* ref_request);
+typedef AZ_NODISCARD az_result (*_az_credential_apply_policy_fn)(
```
Comment (JeffreyRichter) [inline sdk/core/az_core/inc/az_credentials.h:76]: Delete this typedef entirely and use _az_http_policy_process_fn instead. You'll have to move that typedef here.

File: sdk/core/az_core/inc/az_credentials.h [hunk 2]
```diff
@@ -92,7 +95,7 @@ typedef struct
 {
   struct
   {
-    _az_credential_apply_fn apply_credential;
+    _az_credential_apply_policy_fn apply_credential_policy;
```
Comment (JeffreyRichter) [inline sdk/core/az_core/inc/az_credentials.h:98]: Use _az_http_policy_process_fn  instead

File: sdk/core/az_core/inc/az_http_transport.h [hunk 3]
```diff
@@ -168,6 +168,44 @@ AZ_NODISCARD int32_t az_http_request_headers_count(_az_http_request const* reque
...
+
+/**
+ * @brief Defines the callback signature of a policy process which should receive an
+ * _az_http_policy, options reference (as void *), an _az_http_request and az_http_response.
+ *
+ * void * is used as polymorphic solution for any policy. Each policy implementation would know the
+ * specif pointer type to cast options to.
+ *
+ */
+typedef AZ_NODISCARD az_result (*_az_http_policy_process_fn)(
```
Comment (JeffreyRichter) [inline sdk/core/az_core/inc/az_http_transport.h:186]: Move this higher in this .h file

File: sdk/core/az_core/src/az_credential_client_secret.c [hunk 4]
```diff
@@ -48,9 +48,11 @@ static AZ_NODISCARD az_result _az_credential_client_secret_request_token(
 az_span const _az_auth_header_name = AZ_SPAN_LITERAL_FROM_STR("authorization");
 
 // This gets called from the http credential policy
-static AZ_NODISCARD az_result _az_credential_client_secret_apply(
+static AZ_NODISCARD az_result _az_credential_client_secret_apply_policy(
+    _az_http_policy* policies,
     az_credential_client_secret* credential,
-    _az_http_request* ref_request)
+    _az_http_request* ref_request,
```
Comment (JeffreyRichter) [inline sdk/core/az_core/src/az_credential_client_secret.c:54]: Can you please check consistency of parameter names. 
The typedef uses p_policies, p_options, p_request, and p_response.
So, each and every policy function should use the same "p_" prefix and names (except for maybe p_options).
Or, change the "p_" to something else; the important thing is consistency between the typedef and ALL the policy functions.

File: sdk/core/az_core/src/az_credential_client_secret.c [hunk 5]
```diff
@@ -95,7 +92,7 @@ AZ_NODISCARD az_result az_credential_client_secret_init(
     ._internal = {
       .credential = {
         ._internal = {
-          .apply_credential = (_az_credential_apply_fn)_az_credential_client_secret_apply,
+          .apply_credential_policy = (_az_credential_apply_policy_fn)_az_credential_client_secret_apply_policy,
```
Comment (JeffreyRichter) [inline sdk/core/az_core/src/az_credential_client_secret.c:95]: _az_http_policy_process_fn

File: sdk/core/az_core/src/az_http_policy.c [hunk 6]
```diff
@@ -70,11 +60,16 @@ AZ_NODISCARD az_result az_http_pipeline_policy_credential(
     _az_http_request* p_request,
     az_http_response* p_response)
 {
-  if (p_data != AZ_CREDENTIAL_ANONYMOUS)
+  _az_credential* const credential = (_az_credential*)p_data;
```
Comment (JeffreyRichter) [inline sdk/core/az_core/src/az_http_policy.c:63]: I think p_data should be p_options for consistency.
Or, if we could make the 2nd parameter be the right type and the right name, that would be better; we won't have to cast in the function (like this line 63).

File: sdk/core/az_core/src/az_http_policy.c [hunk 7]
```diff
@@ -70,11 +60,16 @@ AZ_NODISCARD az_result az_http_pipeline_policy_credential(
...
+      = credential == NULL ? NULL : credential->_internal.apply_credential_policy;
+
+  if (credential == AZ_CREDENTIAL_ANONYMOUS || policy_credential_apply == NULL)
   {
-    AZ_RETURN_IF_FAILED(_az_apply_credential((_az_credential*)p_data, p_request));
+    return _az_http_pipeline_nextpolicy(p_policies, p_request, p_response);
   }
-  return az_http_pipeline_nextpolicy(p_policies, p_request, p_response);
+
+  return policy_credential_apply(p_policies, credential, p_request, p_response);
```
Comment (JeffreyRichter) [inline sdk/core/az_core/src/az_http_policy.c:72]: Yes, this all looks right - great job!

File: sdk/core/az_core/inc/az_http_transport.h [hunk 8]
```diff
@@ -168,6 +168,44 @@ AZ_NODISCARD int32_t az_http_request_headers_count(_az_http_request const* reque
...
+    _az_http_policy* p_policies,
+    void* p_options,
+    _az_http_request* p_request,
+    az_http_response* p_response);
+
+/**
+ * @brief Definition for an HTTP policy.
+ *
+ * An HTTP pipeline inside SDK clients is made of an array of this http policies.
```
Comment (gilbertw) [inline sdk/core/az_core/inc/az_http_transport.h:195]:
```suggestion
 * An HTTP pipeline inside SDK clients is an array of http policies.
```

File: sdk/core/az_core/src/az_http_policy.c [hunk 9]
```diff
@@ -70,11 +60,16 @@ AZ_NODISCARD az_result az_http_pipeline_policy_credential(
     _az_http_request* p_request,
     az_http_response* p_response)
 {
-  if (p_data != AZ_CREDENTIAL_ANONYMOUS)
```
Comment (gilbertw) [inline sdk/core/az_core/src/az_http_policy.c:73]: Leave this as a PRECONDITION

File: sdk/core/az_core/src/az_http_policy.c [hunk 10]
```diff
@@ -70,11 +60,16 @@ AZ_NODISCARD az_result az_http_pipeline_policy_credential(
...
+  _az_credential* const credential = (_az_credential*)p_data;
+  _az_credential_apply_policy_fn const policy_credential_apply
+      = credential == NULL ? NULL : credential->_internal.apply_credential_policy;
+
+  if (credential == AZ_CREDENTIAL_ANONYMOUS || policy_credential_apply == NULL)
```
Comment (gilbertw) [inline sdk/core/az_core/src/az_http_policy.c:67]: Remove the check for Anonymous.  The policy == null check is sufficient b/c anonymous has a null policy.  Should Anoymous ever change to have a poicy function, then this code doesn't need to change.
```suggestion
  if (policy_credential_apply == NULL)
```

Comment (antkmsft) [reply sdk/core/az_core/src/az_http_policy.c:67]: Anonymous is NULL pointer itself, so we shouldn't read it, and if we try, .policy_credential_apply is most likely going to be initialized with some random data.

File: sdk/core/az_core/src/az_http_policy.c (hunk 9 above)
Comment (antkmsft) [reply sdk/core/az_core/src/az_http_policy.c:73]: As I said below, AZ_CREDENTIAL_ANONYMOUS  is defined as null, so we shouldn't check `NULL->policy_credential_apply == NULL` without checking for NULL first

File: sdk/core/az_core/src/az_credential_client_secret.c (hunk 4 above)
Comment (antkmsft) [reply sdk/core/az_core/src/az_credential_client_secret.c:54]: Done :)

Comment (antkmsft) [reply sdk/core/az_core/src/az_credential_client_secret.c:54]: One thing leads to another, it ended up being touching a lot of files, but on the other hand #496 is mostly done now.

File: sdk/core/az_core/inc/az_credentials.h (hunk 1 above)
Comment (antkmsft) [reply sdk/core/az_core/inc/az_credentials.h]: Done

File: sdk/core/az_core/inc/az_http_transport.h (hunk 3 above)
Comment (antkmsft) [reply sdk/core/az_core/inc/az_http_transport.h]: I moved it as high in this file, as possible.

Comment (antkmsft) [reply sdk/core/az_core/inc/az_http_transport.h]: Done.

File: sdk/core/az_core/inc/az_credentials.h (hunk 2 above)
Comment (antkmsft) [reply sdk/core/az_core/inc/az_credentials.h]: Done.

File: sdk/core/az_core/src/az_credential_client_secret.c (hunk 5 above)
Comment (antkmsft) [reply sdk/core/az_core/src/az_credential_client_secret.c]: Done.

File: sdk/core/az_core/src/az_http_policy.c (hunk 6 above)
Comment (antkmsft) [reply sdk/core/az_core/src/az_http_policy.c]: Done :)

File: sdk/core/az_core/inc/az_http_transport.h (hunk 8 above)
Comment (antkmsft) [reply sdk/core/az_core/inc/az_http_transport.h]: Done :)

**Comment by antkmsft** [comment]
@JeffreyRichter , @gilbertw , I made the changes requested, including unifying all the naming, and I updated namingaccording to guidelines laid out in #496.

File: sdk/core/az_core/src/az_json_parser.c [hunk 11]
```diff
@@ -43,13 +43,13 @@ az_json_parser_stack_last(az_json_parser const* json_parser)
 }
 
 AZ_NODISCARD AZ_INLINE az_result
-az_json_parser_push_stack(az_json_parser* json_parser, _az_json_stack json_stack)
+az_json_parser_push_stack(az_json_parser* ref_json_parser, _az_json_stack json_stack)
```
Comment (ahsonkhan) [inline sdk/core/az_core/src/az_json_parser.c:46]: @antkmsft please avoid making such SDK-wide renaming/refactoring changes to separate PRs outside of unrelated bug fixes/features. This way folks can more easily review and react to them :)

If you happen to touch a file already in a particular PR, then re-formatting or some renaming in that file is fine, but otherwise, I recommend splitting up those changes.
